apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: httpdtest
  namespace: workshop-page
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: httpdtest:latest
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://github.com/camendezl/httpdtest
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: httpd:2.4-el8
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: oF-5vbx57gPA9Myk0nh9
    type: GitHub
  - generic:
      secret: rHF9eKN7D9x1eoL46110
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
