apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpdtest
  namespace: workshop-page
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: httpdtest
  strategy: {}
  template:
    metadata:
      labels:
        deployment: httpdtest
    spec:
      containers:
      - image: 'registry.redhat.io/rhscl/httpd-24-rhel7'
        name: httpdtest
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
