---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: httpdtest
    app.kubernetes.io/component: httpdtest
    app.kubernetes.io/instance: httpdtest
  name: httpdtest
  namespace: workshop-page
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: httpdtest
    app.kubernetes.io/component: httpdtest
    app.kubernetes.io/instance: httpdtest
  name: httpdtest
  namespace: workshop-page
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: httpdtest:latest
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://github.com/camendezl/httpdtest
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: httpd:2.4-el8
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: oF-5vbx57gPA9Myk0nh9
    type: GitHub
  - generic:
      secret: rHF9eKN7D9x1eoL46110
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpdtest
    app.kubernetes.io/component: httpdtest
    app.kubernetes.io/instance: httpdtest
  name: httpdtest
  namespace: workshop-page
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: httpdtest
  strategy: {}
  template:
    metadata:
      labels:
        deployment: httpdtest
    spec:
      containers:
      - image: ' '
        name: httpdtest
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpdtest
    app.kubernetes.io/component: httpdtest
    app.kubernetes.io/instance: httpdtest
  name: httpdtest
  namespace: workshop-page
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deployment: httpdtest
status:
  loadBalancer: {}
