apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: httpdtest
    app.kubernetes.io/component: httpdtest
    app.kubernetes.io/instance: httpdtest
  name: httpdtest
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
