apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: httpdtest
  namespace: workshop-page
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: ""
    name: httpdtest
    weight: null
status: {}
